inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRailsVersion: 8.0
  TargetRubyVersion: 3.4

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
